version: '3.8'
services:
  shareit-gateway:
    build: ./gateway
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - shareit-server
    environment:
      - SHAREIT_SERVER_URL=http://shareit-server:9090

  shareit-server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - shareit-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shareit-db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  shareit-db:
    image: postgres:14.10
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - PGUSER=shareit
      - POSTGRES_PASSWORD=shareit